### ISSUE TITLE
Output Transforms 1.1 - White Point Sim

### ISSUE THREAD

**Issue by remia** [ampas/aces-dev#102]
I noticed that the standard cinema range output transforms perform the scale / rolloff highlight (as part of the white point simulation) in the rendering space (AP1, not pre-compensated) but the new HDR ODTs do this in the display primary space (not pre-compensated). Is there a reason behind this ?

I'm not really sure what happens exactly yet but when using the SSTS methods to design new HDR ODTs using Gamma EOTF, the results seems a bit off. When I move the D60 Sim to be done in AP1, things start to look better.

Hope this make sense.

**Comment by scottdyer** [comment]
@remia good catch! Nobody else caught this is the beta testing phase but it should definitely be done in a consistent space. 

Like the "surround" module, the "white point sim" module is also very much a "placeholder" right now and will definitely need updating with a more robust algorithm to allow for simulation of any white point from any other white point (not just the few hard-coded options currently in there). There are comments noting this in `ACESlib.OutputTransforms.ctl`. This is on the work items for a future release of ACES that more fully utilizes the parameterized output transforms.

I will review the options and push a fix to the hotfixes branch. We will then determine whether to issue a patch release or carry the fix along on the hotfixes branch for now.

**Comment by remia** [comment]
Not that it really matter at the moment, because every HDR ODT target a D65 calibrated display, but I also noticed that in case we don't want to use the D60 simulation, a CAT from D60 to D65 is hardcoded : https://github.com/ampas/aces-dev/blob/master/transforms/ctl/lib/ACESlib.OutputTransforms.ctl#L138

**Comment by scottdyer** [comment]
Superceded by v2.0
