### ISSUE TITLE
Many "ACEStransformID" do not honour "S-2014-002" specification.

### ISSUE THREAD

**Issue by KelSolaar** [ampas/aces-dev#118]
Hi,

As part of the upcoming new ACES OCIO config I'm looking at how much data we can discover and extract from [aces-dev](https://github.com/ampas/aces-dev) itself: https://github.com/colour-science/discover-aces-dev

I'm hitting some roadblocks because many transforms do not honour/respect [S-2014-002](http://j.mp/S-2014-002) specification:

![image](https://user-images.githubusercontent.com/99779/83961064-b3742f80-a8e3-11ea-9e59-b4679f019dd8.png)

Here is the list of offenders, most of them are either not having the three required SEMVER numbers or lack the namespace:

- urn:ampas:aces:transformId:v1.5:IDT.ARRI.Alexa-v2-logC-EI160-CCT3900.**a1.v1**
- urn:ampas:aces:transformId:v1.5:IDT.Sony.SLog1_SGamut_10i.**a1.v1**
- urn:ampas:aces:transformId:v1.5:ACESutil.Lin_to_DolbyPQ.a1.0.3 (No *Academy* namespace)

```
[['reference_implementation/transforms/ctl/idt/vendorSupplied/arri/alexa/v2/EI160/IDT.ARRI.Alexa-v2-logC-EI160-CCT3900.ctl',
  'urn:ampas:aces:transformId:v1.5:IDT.ARRI.Alexa-v2-logC-EI160-CCT3900.a1.v1'],
 ['reference_implementation/transforms/ctl/idt/vendorSupplied/arri/alexa/v2/EI160/IDT.ARRI.Alexa-v2-logC-EI160-CCT6500.ctl',
  'urn:ampas:aces:transformId:v1.5:IDT.ARRI.Alexa-v2-logC-EI160-CCT6500.a1.v1'],
 ['reference_implementation/transforms/ctl/idt/vendorSupplied/arri/alexa/v2/EI160/IDT.ARRI.Alexa-v2-logC-EI160-CCT2000.ctl',
  'urn:ampas:aces:transformId:v1.5:IDT.ARRI.Alexa-v2-logC-EI160-CCT2000.a1.v1'],
 ...['reference_implementation/transforms/ctl/idt/vendorSupplied/arri/alexa/v3/EI3200/IDT.ARRI.Alexa-v3-raw-EI3200-CCT5100-ND1pt3.ctl',
  'urn:ampas:aces:transformId:v1.5:IDT.ARRI.Alexa-v3-raw-EI3200-CCT5100-ND1pt3.a1.v2'],
 ['reference_implementation/transforms/ctl/idt/vendorSupplied/arri/alexa/v3/EI3200/IDT.ARRI.Alexa-v3-raw-EI3200-CCT11000-ND1pt3.ctl',
  'urn:ampas:aces:transformId:v1.5:IDT.ARRI.Alexa-v3-raw-EI3200-CCT11000-ND1pt3.a1.v2'],
 ['reference_implementation/transforms/ctl/idt/vendorSupplied/arri/alexa/v3/EI3200/IDT.ARRI.Alexa-v3-raw-EI3200-CCT4300-ND1pt3.ctl',
  'urn:ampas:aces:transformId:v1.5:IDT.ARRI.Alexa-v3-raw-EI3200-CCT4300-ND1pt3.a1.v2'],
 ['reference_implementation/transforms/ctl/idt/vendorSupplied/sony/IDT.Sony.SLog1_SGamut_10i.ctl',
  'urn:ampas:aces:transformId:v1.5:IDT.Sony.SLog1_SGamut_10i.a1.v1'],
 ['reference_implementation/transforms/ctl/idt/vendorSupplied/sony/IDT.Sony.Venice_SLog3_SGamut3Cine.ctl',
  'urn:ampas:aces:transformId:v1.5:IDT.Sony.Venice_SLog3_SGamut3Cine.a1.v1'],
 ['reference_implementation/transforms/ctl/idt/vendorSupplied/sony/IDT.Sony.SLog2_SGamut_Daylight_12i.ctl',
  'urn:ampas:aces:transformId:v1.5:IDT.Sony.SLog2_SGamut_Daylight_12i.a1.v1'],
 ['reference_implementation/transforms/ctl/idt/vendorSupplied/sony/IDT.Sony.SLog2_SGamut_Tungsten_12i.ctl',
  'urn:ampas:aces:transformId:v1.5:IDT.Sony.SLog2_SGamut_Tungsten_12i.a1.v1'],
 ['reference_implementation/transforms/ctl/idt/vendorSupplied/sony/IDT.Sony.SLog3_SGamut3.ctl',
  'urn:ampas:aces:transformId:v1.5:IDT.Sony.SLog3_SGamut3.a1.v1'],
 ['reference_implementation/transforms/ctl/idt/vendorSupplied/sony/IDT.Sony.Venice_SLog3_SGamut3.ctl',
  'urn:ampas:aces:transformId:v1.5:IDT.Sony.Venice_SLog3_SGamut3.a1.v1'],
 ['reference_implementation/transforms/ctl/idt/vendorSupplied/sony/IDT.Sony.SLog2_SGamut_Tungsten_10i.ctl',
  'urn:ampas:aces:transformId:v1.5:IDT.Sony.SLog2_SGamut_Tungsten_10i.a1.v1'],
 ['reference_implementation/transforms/ctl/idt/vendorSupplied/sony/IDT.Sony.SLog1_SGamut_12i.ctl',
  'urn:ampas:aces:transformId:v1.5:IDT.Sony.SLog1_SGamut_12i.a1.v1'],
 ['reference_implementation/transforms/ctl/idt/vendorSupplied/sony/IDT.Sony.SLog3_SGamut3Cine.ctl',
  'urn:ampas:aces:transformId:v1.5:IDT.Sony.SLog3_SGamut3Cine.a1.v1'],
 ['reference_implementation/transforms/ctl/idt/vendorSupplied/sony/IDT.Sony.SLog2_SGamut_Daylight_10i.ctl',
  'urn:ampas:aces:transformId:v1.5:IDT.Sony.SLog2_SGamut_Daylight_10i.a1.v1'],
 ['reference_implementation/transforms/ctl/utilities/ACESutil.Lin_to_DolbyPQ.ctl',
  'urn:ampas:aces:transformId:v1.5:ACESutil.Lin_to_DolbyPQ.a1.0.3'],
 ['reference_implementation/transforms/ctl/utilities/ACESutil.DolbyPQ_to_Lin.ctl',
  'urn:ampas:aces:transformId:v1.5:ACESutil.DolbyPQ_to_Lin.a1.0.3'],
 ['reference_implementation/transforms/ctl/utilities/ACESutil.Adjust_Exposure.ctl',
  'urn:ampas:aces:transformId:v1.5:ACESutil.Adjust_Exposure.a1.0.3'],
 ['reference_implementation/transforms/ctl/utilities/ACESutil.OCIOshaper_to_Lin_param.ctl',
  'urn:ampas:aces:transformId:v1.5:ACESutil.OCIOshaper_to_Lin_param.a1.0.3'],
 ['reference_implementation/transforms/ctl/utilities/ACESutil.DolbyPQ_to_HLG_1000nits.ctl',
  'urn:ampas:aces:transformId:v1.5:ACESutil.DolbyPQ_to_HLG_1000nits.a1.1.0'],
 ['reference_implementation/transforms/ctl/utilities/ACESutil.Log2_to_Lin_param.ctl',
  'urn:ampas:aces:transformId:v1.5:ACESutil.Log2_to_Lin_param.a1.0.3'],
 ['reference_implementation/transforms/ctl/utilities/ACESutil.premultAlpha_to_straightAlpha.ctl',
  'urn:ampas:aces:transformId:v1.5:ACESutil.premultAlpha_to_straightAlpha.a1.0.3'],
 ['reference_implementation/transforms/ctl/utilities/ACESutil.Lin_to_OCIOshaper_param.ctl',
  'urn:ampas:aces:transformId:v1.5:ACESutil.Lin_to_OCIOshaper_param.a1.0.3'],
 ['reference_implementation/transforms/ctl/utilities/ACESutil.HLG_to_DolbyPQ_1000nits.ctl',
  'ACESutil.HLG_to_DolbyPQ_1000nits.a1.1.0'],
 ['reference_implementation/transforms/ctl/utilities/ACESutil.straightAlpha_to_premultAlpha.ctl',
  'urn:ampas:aces:transformId:v1.5:ACESutil.straightAlpha_to_premultAlpha.a1.0.3'],
 ['reference_implementation/transforms/ctl/utilities/ACESutil.Unity.ctl',
  'urn:ampas:aces:transformId:v1.5:ACESutil.Unity.a1.0.3'],
 ['reference_implementation/transforms/ctl/utilities/ACESutil.Lin_to_Log2_param.ctl',
  'urn:ampas:aces:transformId:v1.5:ACESutil.Lin_to_Log2_param.a1.0.3'],
 ['reference_implementation/transforms/ctl/outputTransforms/RRTODT.Academy.P3D65_108nits_7.2nits_ST2084.ctl',
  'urn:ampas:aces:transformId:v1.5:RRTODT.Academy.P3D65_108nits_7.2nits_ST2084.a1.1.0'],
 ['reference_implementation/transforms/ctl/outputTransforms/InvRRTODT.Academy.P3D65_108nits_7.2nits_ST2084.ctl',
  'urn:ampas:aces:transformId:v1.5:InvRRTODT.Academy.P3D65_108nits_7.2nits_ST2084.a1.1.0'],
 ['reference_implementation/transforms/ctl/csc/canon/ACEScsc.Academy.ACES_to_CLog3_CGamut.ctl',
  'ACEScsc.ACES_to_CLog3_CGamut.a1.v1'],
 ['reference_implementation/transforms/ctl/csc/canon/ACEScsc.Academy.CLog3_CGamut_to_ACES.ctl',
  'ACEScsc.CLog3_CGamut_to_ACES.a1.v1'],
 ['reference_implementation/transforms/ctl/csc/canon/ACEScsc.Academy.ACES_to_CLog2_CGamut.ctl',
  'ACEScsc.ACES_to_CLog2_CGamut.a1.v1'],
 ['reference_implementation/transforms/ctl/csc/canon/ACEScsc.Academy.CLog2_CGamut_to_ACES.ctl',
  'ACEScsc.CLog2_CGamut_to_ACES.a1.v1'],
 ['reference_implementation/transforms/ctl/csc/red/ACEScsc.Academy.ACES_to_Log3G10_RWG.ctl',
  'ACEScsc.ACES_to_Log3G10_RWG.a1.v1'],
 ['reference_implementation/transforms/ctl/csc/red/ACEScsc.Academy.Log3G10_RWG_to_ACES.ctl',
  'ACEScsc.Log3G10_RWG_to_ACES.a1.v1'],
 ['reference_implementation/transforms/ctl/csc/arri/ACEScsc.Academy.ACES_to_LogC_EI800_AWG.ctl',
  'ACEScsc.ACES_to_LogC_EI800_AWG.a1.v1'],
 ['reference_implementation/transforms/ctl/csc/arri/ACEScsc.Academy.LogC_EI800_AWG_to_ACES.ctl',
  'ACEScsc.LogC_EI800_AWG_to_ACES.a1.v1'],
 ['reference_implementation/transforms/ctl/csc/panasonic/ACEScsc.Academy.ACES_to_VLog_VGamut.ctl',
  'ACEScsc.ACES_to_VLog_VGamut.a1.v1'],
 ['reference_implementation/transforms/ctl/csc/panasonic/ACEScsc.Academy.VLog_VGamut_to_ACES.ctl',
  'ACEScsc.VLog_VGamut_to_ACES.a1.v1'],
 ['reference_implementation/transforms/ctl/csc/sony/ACEScsc.Academy.ACES_to_SLog3_SGamut3Cine.ctl',
  'ACEScsc.ACES_to_SLog3_SGamut3Cine.a1.v1'],
 ['reference_implementation/transforms/ctl/csc/sony/ACEScsc.Academy.SLog3_SGamut3Cine_to_ACES.ctl',
  'ACEScsc.SLog3_SGamut3Cine_to_ACES.a1.v1'],
 ['reference_implementation/transforms/ctl/csc/sony/ACEScsc.Academy.ACES_to_SLog3_SGamut3.ctl',
  'ACEScsc.ACES_to_SLog3_SGamut3.a1.v1'],
 ['reference_implementation/transforms/ctl/csc/sony/ACEScsc.Academy.SLog3_SGamut3_to_ACES.ctl',
  'ACEScsc.SLog3_SGamut3_to_ACES.a1.v1'],
 ['reference_implementation/transforms/ctl/lib/ACESlib.OutputTransforms.ctl',
  'urn:ampas:aces:transformId:v1.5:ACESlib.OutputTransforms.a1.1.0'],
 ['reference_implementation/transforms/ctl/lib/ACESlib.ODT_Common.ctl',
  'urn:ampas:aces:transformId:v1.5:ACESlib.ODT_Common.a1.1.0'],
 ['reference_implementation/transforms/ctl/lib/ACESlib.Utilities_Color.ctl',
  'urn:ampas:aces:transformId:v1.5:ACESlib.Utilities_Color.a1.1.0'],
 ['reference_implementation/transforms/ctl/lib/ACESlib.Tonescales.ctl',
  'urn:ampas:aces:transformId:v1.5:ACESlib.Tonescales.a1.0.3'],
 ['reference_implementation/transforms/ctl/lib/ACESlib.Transform_Common.ctl',
  'urn:ampas:aces:transformId:v1.5:ACESlib.Transform_Common.a1.0.3'],
 ['reference_implementation/transforms/ctl/lib/ACESlib.RRT_Common.ctl',
  'urn:ampas:aces:transformId:v1.5:ACESlib.RRT_Common.a1.1.0'],
 ['reference_implementation/transforms/ctl/lib/ACESlib.SSTS.ctl',
  'urn:ampas:aces:transformId:v1.5:ACESlib.SSTS.a1.1.0'],
 ['reference_implementation/transforms/ctl/lib/ACESlib.Utilities.ctl',
  'urn:ampas:aces:transformId:v1.5:ACESlib.Utilities.a1.0.3']]
```

**Comment by KelSolaar** [comment]
Adding @JGoldstone to the party! :)

**Comment by KelSolaar** [comment]
Something like that fixes all the current `ACEStransformID ` on my end and gives an idea of all the problems:

```python
def patch_invalid_id(id_):
    if not id_.startswith(ACES_URN):
        id_ = f'{ACES_URN}:{id_}'

    if id_.endswith('a1.v1'):
        id_ = id_.replace('a1.v1', 'a1.1.0')

    if id_.endswith('a1.v2'):
        id_ =  id_.replace('a1.v2', 'a1.2.0')

    if 'Academy.P3D65_108nits_7.2nits_ST2084' in id_:
        return id_.replace('7.2', '7')
    elif 'ACEScsc' in id_ and not 'ACEScsc.Academy' in id_:
        return id_.replace('ACEScsc', 'ACEScsc.Academy')
    elif 'ACESlib' in id_ and not 'ACESlib.Academy' in id_:
        return id_.replace('ACESlib', 'ACESlib.Academy')
    elif 'ACESutil' in id_ and not 'ACESutil.Academy' in id_:
        return id_.replace('ACESutil', 'ACESutil.Academy')
    else:
        return id_
```

**Comment by scottdyer** [comment]
> urn:ampas:aces:transformId:v1.5:IDT.ARRI.Alexa-v2-logC-EI160-CCT3900.a1.v1
> urn:ampas:aces:transformId:v1.5:IDT.Sony.SLog1_SGamut_10i.a1.v1

These are correct according to 4.6.1

**4.6.1 Input Transforms (IDTs)**
_URN:**IDT**.Namespace.DeviceName.**a**ACESmajorVersionNumber.**v**IDTversionNumber_

> urn:ampas:aces:transformId:v1.5:ACESutil.Lin_to_DolbyPQ.a1.0.3 (No Academy namespace)

Also correct according to 4.5.3. (whether or not the way 4.5.3 is written makes sense is a separate issue)

**4.5.3 ACES Core Libraries and Utilities**
Academy-supplied core libraries and utilities’ major version number shall match the ACES System Version Major Version number. Core library and utilities Transform Identifiers shall use the following versioning convention:
_URN:**ACESlib**.Name.**a**ACESmajorVersionNumber.ACESlibMinorVersionNumber.ACESlib PatchVersionNumber_
_URN:**ACESutil**.Name.**a**ACESmajorVersionNumber.ACESutilMinorVersionNumber.ACES utilPatchVersionNumber_

**Comment by KelSolaar** [comment]
Thanks @scottdyer! I did not read further that section 4.1 because I was naive in assuming that the specification was consistent which it is not!

A few things then:

- I reckon that a note should be added in Section 4.1 that the convention is not consistent across transforms, i.e. _where applicable_ is not enough.
- `ACESutil.HLG_to_DolbyPQ_1000nits.a1.1.0` is missing the URN
- `urn:ampas:aces:transformId:v1.5:RRTODT.Academy.P3D65_108nits_7.2nits_ST2084.a1.1.0` is invalid because the name is split in two with the dot in `7.2nits`.

I will update my code tonight and see what is left!

**Comment by scottdyer** [comment]
Yeah, it's extremely confusing. There are almost certainly transforms that were missed when the transform IDs were last updated to add the urn prefix. I used a multi-file find & replace and so if there were any deviations from the match pattern I used then I probably missed one or two. We can fix them all once we think we've found them all.

**Comment by KelSolaar** [comment]
Some of the ACEScsc are not correct:

![image](https://user-images.githubusercontent.com/99779/83994853-bc303880-a9ab-11ea-9595-03af0deb5e9c.png)

> // <ACEStransformID>ACEScsc.CLog2_CGamut_to_ACES.a1.v1</ACEStransformID>

No URN and no patch version number!

**Comment by KelSolaar** [comment]
Kind of validates the point that there should only be a single naming convention, the first one described in the spec :)

**Comment by KelSolaar** [comment]
Here is the current list of ugly ducklings if we are sticking to the current spec:

Missing URN
---

- ACESutil.HLG_to_DolbyPQ_1000nits.a1.1.0
- ACEScsc.ACES_to_CLog3_CGamut.a1.v1
- ACEScsc.CLog3_CGamut_to_ACES.a1.v1
- ACEScsc.ACES_to_CLog2_CGamut.a1.v1
- ACEScsc.CLog2_CGamut_to_ACES.a1.v1
- ACEScsc.ACES_to_Log3G10_RWG.a1.v1
- ACEScsc.Log3G10_RWG_to_ACES.a1.v1
- ACEScsc.ACES_to_LogC_EI800_AWG.a1.v1
- ACEScsc.LogC_EI800_AWG_to_ACES.a1.v1
- ACEScsc.ACES_to_VLog_VGamut.a1.v1
- ACEScsc.VLog_VGamut_to_ACES.a1.v1
- ACEScsc.ACES_to_SLog3_SGamut3Cine.a1.v1
- ACEScsc.SLog3_SGamut3Cine_to_ACES.a1.v1
- ACEScsc.ACES_to_SLog3_SGamut3.a1.v1
- ACEScsc.SLog3_SGamut3_to_ACES.a1.v1

Invalid Separator
---
- urn:ampas:aces:transformId:v1.5:RRTODT.Academy.P3D65_108nits_7.2nits_ST2084.a1.1.0
- urn:ampas:aces:transformId:v1.5:InvRRTODT.Academy.P3D65_108nits_7.2nits_ST2084.a1.1.0

Missing Namespace
---
- urn:ampas:aces:transformId:v1.5:ACEScsc.ACES_to_CLog3_CGamut.a1.v1
- urn:ampas:aces:transformId:v1.5:ACEScsc.CLog3_CGamut_to_ACES.a1.v1
- urn:ampas:aces:transformId:v1.5:ACEScsc.ACES_to_CLog2_CGamut.a1.v1
- urn:ampas:aces:transformId:v1.5:ACEScsc.CLog2_CGamut_to_ACES.a1.v1
- urn:ampas:aces:transformId:v1.5:ACEScsc.ACES_to_Log3G10_RWG.a1.v1
- urn:ampas:aces:transformId:v1.5:ACEScsc.Log3G10_RWG_to_ACES.a1.v1
- urn:ampas:aces:transformId:v1.5:ACEScsc.ACES_to_LogC_EI800_AWG.a1.v1
- urn:ampas:aces:transformId:v1.5:ACEScsc.LogC_EI800_AWG_to_ACES.a1.v1
- urn:ampas:aces:transformId:v1.5:ACEScsc.ACES_to_VLog_VGamut.a1.v1
- urn:ampas:aces:transformId:v1.5:ACEScsc.VLog_VGamut_to_ACES.a1.v1
- urn:ampas:aces:transformId:v1.5:ACEScsc.ACES_to_SLog3_SGamut3Cine.a1.v1
- urn:ampas:aces:transformId:v1.5:ACEScsc.SLog3_SGamut3Cine_to_ACES.a1.v1
- urn:ampas:aces:transformId:v1.5:ACEScsc.ACES_to_SLog3_SGamut3.a1.v1
- urn:ampas:aces:transformId:v1.5:ACEScsc.SLog3_SGamut3_to_ACES.a1.v1

Invalid Versioning
---
- urn:ampas:aces:transformId:v1.5:ACEScsc.ACES_to_CLog3_CGamut.a1.v1
- urn:ampas:aces:transformId:v1.5:ACEScsc.CLog3_CGamut_to_ACES.a1.v1
- urn:ampas:aces:transformId:v1.5:ACEScsc.ACES_to_CLog2_CGamut.a1.v1
- urn:ampas:aces:transformId:v1.5:ACEScsc.CLog2_CGamut_to_ACES.a1.v1
- urn:ampas:aces:transformId:v1.5:ACEScsc.ACES_to_Log3G10_RWG.a1.v1
- urn:ampas:aces:transformId:v1.5:ACEScsc.Log3G10_RWG_to_ACES.a1.v1
- urn:ampas:aces:transformId:v1.5:ACEScsc.ACES_to_LogC_EI800_AWG.a1.v1
- urn:ampas:aces:transformId:v1.5:ACEScsc.LogC_EI800_AWG_to_ACES.a1.v1
- urn:ampas:aces:transformId:v1.5:ACEScsc.ACES_to_VLog_VGamut.a1.v1
- urn:ampas:aces:transformId:v1.5:ACEScsc.VLog_VGamut_to_ACES.a1.v1
- urn:ampas:aces:transformId:v1.5:ACEScsc.ACES_to_SLog3_SGamut3Cine.a1.v1
- urn:ampas:aces:transformId:v1.5:ACEScsc.SLog3_SGamut3Cine_to_ACES.a1.v1
- urn:ampas:aces:transformId:v1.5:ACEScsc.ACES_to_SLog3_SGamut3.a1.v1
- urn:ampas:aces:transformId:v1.5:ACEScsc.SLog3_SGamut3_to_ACES.a1.v1

**Comment by JGoldstone** [comment]
Hello all—

Yikes. Just catching up on non-ARRI email; about 600 messages built up in ‘unread’ in the last 10 days or so. Thanks for adding me.

My eyebrows go up when I see LogC and AWG used that way. The original LogC and AWG were before my time. LogCv2 was in use in content shot on the ALEXA in 2010, superseded by LogCv3 and AWG3 [yes, I know, inconsistent naming] with ALEXA SUP 3.0 just before I arrived at ARRI in January 2011. Seeing CLog3, CLog2, &c below without seeing LogCv3 (or if you wish, LogC3) is problematic.

We did contribute transforms for both the second and third versions of the LogC transforms to the ACES repository. Maybe three or four years back, at the urging of a key VFX facility that processes a lot of ALEXA content, I updated the LogCV3 transforms to fix some slight inaccuracies at EI 1600, and increasing inaccuracy as you went up to EI 3200 where the ALEXA tops out. (In order to do that, and have inverse transforms, I had to switch to generating great big 1D LUTs, rather than executable formulae, but that’s another story.)

Almost certainly ALEXA LogCv3 won’t be the last log encoding curve from ARRI nor will AWG3 be the last encoding gamut from ARRI.

Can we say with confidence that the transform IDs below, having no LogC version qualifier in their names, are LogCV3, AWG3?
Part of me wants to say that we should retain the names below, but make the transforms be the equivalent of symbolic links to transforms that have names that more accurately reflect their contents. But I don’t know if we have the capability. (If the non-versioned transform is just an include of the V3 version, could that work?)

The only schedule-related thing we’ve said about a new camera product is that there will be one in 2021. Can we get this cleaned up by then?

Best—
—joseph

**Comment by KelSolaar** [comment]
> Can we get this cleaned up by then?

I hope so!

@scottdyer, @aforsythe : Here is another one whose ACESTransformID is incorrect:

https://github.com/ampas/aces-dev/blob/e83c7d9cbff316e25353a0e93ef4b7f40a403e08/transforms/ctl/odt/rec2020/ODT.Academy.Rec2020_P3D65limited_100nits_dim.ctl#L2

`s/Rec2020_100nits/Rec2020_P3D65limited_100nits_dim`

**Comment by KelSolaar** [comment]
I just found out two other problematic ones that are fine from a specification standpoint but are not consistent:

# odt/p3/ODT.Academy.P3D65_Rec709limited_48nits.ctl

https://github.com/ampas/aces-dev/blob/master/transforms/ctl/odt/p3/ODT.Academy.P3D65_Rec709limited_48nits.ctl

`// <ACEStransformID>urn:ampas:aces:transformId:v1.5:ODT.Academy.P3D65_709limit_48nits.a1.1.0</ACEStransformID>`

`709limit` where all the other ones will consistently use `Rec` and `limited`:

- `ODT.Academy.Rec2020_Rec709limited_100nits.a1.1.0`
- `InvODT.Academy.DCDM_P3D65limited.a1.1.0`
- `ODT.Academy.Rec2020_Rec709limited_100nits.a1.1.0`

# odt/rec2020/ODT.Academy.Rec2020_P3D65limited_100nits_dim.ctl

https://github.com/ampas/aces-dev/blob/master/transforms/ctl/odt/rec2020/ODT.Academy.Rec2020_P3D65limited_100nits_dim.ctl

This one is probably worse because nothing says in its ID name that it is P3D65 limited:

- `ODT.Academy.Rec2020_100nits.a1.1.0`

**Comment by KelSolaar** [comment]
This one should be fine to close now!
