### ISSUE TITLE
Clamp in ACEScsc.ACES-to-ACEScg.ctl

### ISSUE THREAD

**Issue by scottdyer** [ampas/aces-dev#122]
https://github.com/ampas/aces-dev/blob/518c27f577e99cdecfddf2ebcfaa53444b1f9343/transforms/ctl/csc/ACEScg/ACEScsc.Academy.ACES_to_ACEScg.ctl#L32

This clamp seems erroneous. None of the other color space conversion transforms contain a similar clamp and this seems wrong as it breaks reversibility - any valid ACES (AP0) values outside of the AP1 triangle would be lost if converted to ACEScg and back.

Is there a reason why this clamp is here? 
Would removing this break anything for CG artists?

**Comment by KelSolaar** [comment]
Sure feel like it should not be here!

**Comment by scottdyer** [comment]
This was fixed in 68572c1
