### ISSUE TITLE
Direction comment should be removed

### ISSUE THREAD

**Issue by nick-shaw** [ampas/aces-dev#128]
https://github.com/ampas/aces-dev/blob/d3d4df5f0095dfa663bee768ff57c8b9135ebb05/transforms/ctl/lmt/LMT.Academy.ReferenceGamutCompress.ctl#L18

The reference to the `direction` runtime flag is no longer correct, since the forward and inverse LMTs have been split into separate transforms.

**Comment by scottdyer** [comment]
Fixed in v2 Developer Release
See https://github.com/ampas/aces-look/commit/e0e70ecf2ce57d503318dde1fa4aa1bd7287fcdd
