### ISSUE TITLE
Usage comment inapplicable to inverse LMT

### ISSUE THREAD

**Issue by nick-shaw** [ampas/aces-dev#129]
https://github.com/ampas/aces-dev/blob/d3d4df5f0095dfa663bee768ff57c8b9135ebb05/transforms/ctl/lmt/InvLMT.Academy.ReferenceGamutCompress.ctl#L10

This copy of the usage comment from the forward transform is not correct for the inverse transform. A gamut expansion may well create negative AP1 values, where they were previously not present.

While the forward transform should always be used straight after the IDT, this would not necessarily be the case for an inverse transform. The place where it is used will vary, depending on its intended purpose.

I suggest the usage note would be better emphasising that the use of the inverse is not normally recommended, and words to the effect that you use it "at your own risk" and in whatever position is appropriate to your pipeline. The inverse is provided for completeness, with these caveats.

**Comment by scottdyer** [comment]
Fixed in v2.0 Developer Release.
See https://github.com/ampas/aces-look/commit/b931ef8cc2ccdb25ab6c16c5c77ccb40a5de7baf
