### ISSUE TITLE
broken link on https://github.com/ampas/aces-dev/tree/dev/transforms/ctl/idt/vendorSupplied/panasonic

### ISSUE THREAD

**Issue by marekjez86** [ampas/aces-dev#133]
I know that the content at https://github.com/ampas/aces-dev/tree/dev/transforms/ctl/idt/vendorSupplied/panasonic may be vendor supplied, but the link there is listed as

http://pro-av.panasonic.net/en/varicam/35/dl.html is broken, and it

should be
https://pro-av.panasonic.net/en/cinema_camera_varicam_eva/support/download_data/idt_panasonic_forV35_ver100.zip

or https://pro-av.panasonic.net/en/cinema_camera_varicam_eva/support/index.html (search for ACES)

Marek

PS. I'm taking a course from UCLA Extension by Barry Goch titled "386825: Post-Production for Film and Television FILM TV X 404A (Summer 2022)". The final project requires me to design a workflow. I wanted to do it using ACES and my own Panasonic S1H (I'm still not sure if it's possible, but I'll learn something)

**Comment by scottdyer** [comment]
CTL versions of the Varicam IDT are included in https://github.com/ampas/aces-input-and-colorspaces/tree/main/panasonic
