### ISSUE TITLE
Inconsistent and possibly incorrect `ACEStransformID` for ARRI LogC4

### ISSUE THREAD

**Issue by KelSolaar** [ampas/aces-dev#138]
Hello,

There is an issue with the ARRI LogC 4 *ACEStransformID*:

## *aces-dev* - LogC4

https://github.com/ampas/aces-dev/blob/dev/transforms/ctl/idt/vendorSupplied/arri/alexa/v4/IDT.ARRI.ARRI-LogC4.ctl#L1

> urn:ampas:aces:transformId:v1.5:IDT.ARRI.ARRI-LogC4.a1.v1

## *aces-dev* - LogC3

https://github.com/ampas/aces-dev/blob/dev/transforms/ctl/idt/vendorSupplied/arri/alexa/v3/EI800/IDT.ARRI.Alexa-v3-logC-EI800.ctl#L2

> urn:ampas:aces:transformId:v1.5:IDT.ARRI.Alexa-v3-logC-EI800.a1.v2

## *OpenColorIO-Config-ACES* - LogC4

https://github.com/AcademySoftwareFoundation/OpenColorIO-Config-ACES/blob/main/opencolorio_config_aces/clf/transforms/arri/generate.py#L345

> urn:ampas:aces:transformId:v1.5:IDT.ARRI.LogC4.a1.v1

One of the *aces-dev* IDT or *OpenColorIO-Config-ACES* CLF is incorrect. I think that the *aces-dev* IDT is inconsistent but no strong opinion as to what should be done here.

That being said we are trying to release a new OpenColorIO version along side new builtin configs so it would be awesome to get a resolution as soon as possible.

@scoopxyz, @Doug-walker, @aforsythe for VIS.

**Comment by KelSolaar** [comment]
@doug-walker and I (and Carol) decided to change it on the OCIO side as it is easier and gets us moving.

**Comment by scoopxyz** [comment]
Copying my response from the Colour-Science slack thread:

>  I had to go back and look at why we chose the present form. If I look at the LogC3 EI 800 IDT that is:
> `IDT.ARRI.Alexa-v3-logC-EI800.a1.v2`
> 
> And the present LogC4 is:
> `IDT.ARRI.ARRI-LogC4.a1.v1`
> 
> This is something like `<Class>.<Vendor>.<ColorSpaceName>.<ACESVersion>.<Version>`
> 
> So "ARRI LogC4" is the official name of the color space, with its component parts being "ARRI Wide Gamut 4" and "ARRI LogC4 Curve". This information is also mirrored in the white paper. So I would actually vote to have the aces-dev TransformID remain as-is. Despite the quasi-ugliness of having the vendor name appear twice.
> 
> I'm open to be convinced in another direction, but that is my reasoning.
> 
> As to why its different in the OpenColorIO Config, this was based on the observation that it already takes "creative" liberty in the ACES ID. For example between...
> https://github.com/AcademySoftwareFoundation/OpenColorIO-Config-ACES/blob/9a1ddea03ae1367d1802b8811db27eade40db688/opencolorio_config_aces/clf/transforms/sony/generate.py#L139
> 
> ...and...
> 
> https://github.com/ampas/aces-dev/blob/ea2afeb4d4f3cd788e42da56787daf0dd465dec2/transforms/ctl/idt/vendorSupplied/sony/IDT.Sony.Venice_SLog3_SGamut3.ctl#L1C4-L1C106
> 
> Which influenced the OCIO config discussion, in addition to the conversation with Doug in the PR: https://github.com/AcademySoftwareFoundation/OpenColorIO-Config-ACES/pull/54
> 
> 
> I can repeat this in the OCIO slack as well.

**Comment by scoopxyz** [comment]
So to summarize this specific issue, it seems like it is different because it was different "on purpose", and there are other instances of the ACESTransformID not being the same as the `aces-dev` repo.

**Comment by doug-walker** [comment]
Thanks for looking into this Sean!  Thomas changed the ADESTransformID in the OCIO config to match what is in aces-dev, so they are both `urn:ampas:aces:transformId:v1.5:IDT.ARRI.ARRI-LogC4.a1.v1`.  I confirmed that this is what is in the latest built-in OCIO configs.

I think this issue could be closed now.

**Comment by KelSolaar** [comment]
Thanks, let's close that one as resolved!

**Comment by KelSolaar** [comment]
(I will indicate that we changed the ACEStransformID in the config release notes.)
