### ISSUE TITLE
BUG: cusp lookups do not wrap correctly

### ISSUE THREAD

**Issue by nick-shaw** [ampas/aces-dev#148]
Comments in the CTL code refer to "allowed as we have an extra entry in the table" but the table size is declared [here](https://github.com/ampas/aces-dev/blob/0b632da885c29f1ca8e816b3995ad5fde976e9ae/lib/Lib.Academy.OutputTransform.ctl#L25) as only 360.

When rendering the dominant wavelength image (which runs around the entire hue circle) through the Rec.709 Output Transform, an exception is thrown at line [536](https://github.com/ampas/aces-dev/blob/0b632da885c29f1ca8e816b3995ad5fde976e9ae/lib/Lib.Academy.OutputTransform.ctl#L536) 
```
../aces-dev/lib/Lib.Academy.OutputTransform.ctl:536: Array index out of range (index = -1, array size = 360).
```

**Comment by scottdyer** [comment]
> It does indeed appear that inf pixels in the source result in NaN JMh values, which makes the iteration in the hue lookup fail, (`nan <= something` and `nan >= something` are both false) resulting in an index of -1. Clamping the input to a finite value (16384 has been found to be a good candidate) during the AP1 clamp, instead of `HALF_POS_INF` resolves the issue.

Separated this into its own issue (#147) and keep this one dedicated to the LUT lookup indexing.

**Comment by scottdyer** [comment]
(In reference to the `high_i = gamutTableSize -1`, @KevinJW or @nick-shaw, in what case would this be expected error?  Or will it just return a value off by 1? 

I'm trying to make a test that forces it to fail, but I can't find an instance where `cuspFromTable()` is not returning a value. It seems to be working as expected, but maybe I am not thinking of the case where it could fail. I am generating hues from -135 to 720 in 0.9 increments, so they won't all fall on integer values, and then using that hue (wrapped to 360) to look up J and M from a 100-nit Rec. 709 gamut table.

**Comment by scottdyer** [comment]
A protection for this was attempted in b631619cd0f206b1bf3b233e78994d4cf4bebfbe, 202c04a4caf130a679d356069cde563294c56887 and 35fd7a393ef35aeff7b1a2aa563f956e31c8b849
