### ISSUE TITLE
Two `compressionFuncParams` values are unused

### ISSUE THREAD

**Issue by nick-shaw** [ampas/aces-dev#151]
https://github.com/ampas/aces-dev/blob/0b632da885c29f1ca8e816b3995ad5fde976e9ae/lib/Lib.Academy.OutputTransform.ctl#L23

Only `[0]` and `[3]` from the array of values get used, with `[3]` being the 1.0 exponent for powerP. Values `[1]` and `[2]` were only ever used in non-reach mode, which is not included in the CTL.

I reality, only a single `compressionThreshold` value is needed (and it's purpose would be clearer from the name) if the compression curve is simplified to Reinhard.

**Comment by scottdyer** [comment]
Commit faf617a01a54eb553f58ccb330630c5284a122bc addresses this issue
