### ISSUE TITLE
J column in the cGamutCusp table is unused

### ISSUE THREAD

**Issue by nick-shaw** [ampas/aces-dev#152]
The J column never gets used, so doesn't need to be stored. Only M is used for normalisation

https://github.com/ampas/aces-dev/blob/0b632da885c29f1ca8e816b3995ad5fde976e9ae/lib/Lib.Academy.OutputTransform.ctl#L616

**Comment by nick-shaw** [comment]
Additionally, `REACH_GAMUT_TABLE` is probably not the right name, as this one is the cusp, but the table of M values at `limitJmax` gets called `REACH_CUSP_TABLE`.

**Comment by scottdyer** [comment]
Commit e1b72c91da03586b378fe10b355a714147e2500d addresses this issue
