### ISSUE TITLE
Broken documents link in README.md

### ISSUE THREAD

**Issue by reinecke** [ampas/aces-dev#154]
The README.md includes this paragraph:

> File names conform to the ACES System Versioning Specification. Details can be found in the Academy Specification "S-2014-002 - Academy Color Encoding System - Versioning System" included in [documents/](https://github.com/ampas/aces-dev/blob/dev/documents)

However the `documents` directory linked leads to a 404 - ideally the document could be found from that link.

**Comment by scottdyer** [comment]
This is an old README. Documentation has been at docs.acescentral.com for a few years
