### ISSUE TITLE
Homebrew's bottled CTL 1.5.2 links against non-current IlmBase (Iex)

### ISSUE THREAD

**Issue by JGoldstone** [ampas/aces-dev#57]
Perhaps I'm misunderstanding how brew works, but it appears that the bottled ctl contains compiled libraries that reference obsolete compiled libraries, specifically libIex-2_1.11. Problem and workaround:

 57 % brew install ctl
==> Installing dependencies for ctl: ilmbase, openexr
==> Installing ctl dependency: ilmbase
==> Downloading https://homebrew.bintray.com/bottles/ilmbase-2.2.0.yosemite.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/ilmbase-2.2.0.yosemite.bottle.tar.gz
==> Pouring ilmbase-2.2.0.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/ilmbase/2.2.0: 347 files, 6.4M
==> Installing ctl dependency: openexr
==> Downloading https://homebrew.bintray.com/bottles/openexr-2.2.0.yosemite.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/openexr-2.2.0.yosemite.bottle.tar.gz
==> Pouring openexr-2.2.0.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/openexr/2.2.0: 129 files, 12M
==> Installing ctl
==> Downloading https://homebrew.bintray.com/bottles/ctl-1.5.2.yosemite.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/ctl-1.5.2.yosemite.bottle.tar.gz
==> Pouring ctl-1.5.2.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/ctl/1.5.2: 45 files, 3.9M
 58 % otool -L /usr/local/lib/libIlmCtl.1.5.0.dylib
/usr/local/lib/libIlmCtl.1.5.0.dylib:
    /usr/local/lib/libIlmCtl.1.5.0.dylib (compatibility version 1.5.0, current version 1.5.0)
    /usr/local/lib/libIex-2_1.11.dylib (compatibility version 12.0.0, current version 12.0.0)
    /usr/local/lib/libIlmThread-2_1.11.dylib (compatibility version 12.0.0, current version 12.0.0)
    /usr/local/lib/libHalf.11.dylib (compatibility version 12.0.0, current version 12.0.0)
    /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
 59 % man brew
 60 % brew uninstall ctl
Uninstalling /usr/local/Cellar/ctl/1.5.2... (45 files, 3.9M)
 61 % brew install ctl --build-from-source
==> Downloading https://github.com/ampas/CTL/archive/ctl-1.5.2.tar.gz
###### ################################################################## 100.0%

==> cmake .. -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/ctl/1.5.2 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -
==> make
==> make check
==> make install
🍺  /usr/local/Cellar/ctl/1.5.2: 47 files, 3.9M, built in 38 seconds
 62 % !otool
otool -L /usr/local/lib/libIlmCtl.1.5.0.dylib
/usr/local/lib/libIlmCtl.1.5.0.dylib:
    /usr/local/lib/libIlmCtl.1.5.0.dylib (compatibility version 1.5.0, current version 1.5.0)
    /usr/local/lib/libIex-2_2.12.dylib (compatibility version 13.0.0, current version 13.0.0)
    /usr/local/lib/libIlmThread-2_2.12.dylib (compatibility version 13.0.0, current version 13.0.0)
    /usr/local/lib/libHalf.12.dylib (compatibility version 13.0.0, current version 13.0.0)
    /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
 63 %

**Comment by yuanliuvsco** [comment]
You can manually build and install ilmbase 2.1 from source after install CTL from brew

**Comment by JGoldstone** [comment]
Right, but if I'm going to be forced to do something manually, why not just supply --build-from-source and get the more modern libraries? My point was that with ilmbase 2.2 being out, brewing CTL should not require manual intervention.

**Comment by aforsythe** [comment]
Agreed ... manual intervention shouldn't be required.

The current formula specifies the SHA ID for various bottles, but I'm not sure what those bottles are or where they are located.

How do we update the formula to point to the right IlmBase Bottle?

[?]<http://www.oscars.org>


Alex Forsythe
Image Engineering Manager


Academy of Motion Picture Arts and Sciences
Science & Technology Council
1313 Vine Street • Hollywood, CA 90028


323.817.4170 • aforsythe@oscars.org<mailto:aforsythe@oscars.org>

**Comment by cbenhagen** [comment]
@aforsythe
If you just want the bottle to be rebuilt you can make a pull request which updates the bottle revision https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Bottles.md#revision

@JGoldstone 
The CTL bottle has been rebuilt a month ago. This should have fixed your issue right?

**Comment by scottdyer** [comment]
Cleaning up old open issues...
