### ISSUE TITLE
Dead Link from Academy Oscars.org Page

### ISSUE THREAD

**Issue by sobotka** [ampas/aces-dev#72]
The page http://www.oscars.org/science-technology/sci-tech-projects/aces has a dead link to the ACES 1.0 OpenColorIO links here https://github.com/hpd/OpenColorIO-Configs/tree/master/aces_1.0.0

**Comment by scottdyer** [comment]
Thanks @sobotka  The link has been updated to the aces_1.0.1 OCIO config.
