### ISSUE TITLE
License Confirmation?

### ISSUE THREAD

**Issue by sobotka** [ampas/aces-dev#76]
I'd like to use portions of the Python configuration builders in the OpenColorIO ACES configurations repository, but there is no attached license for this.

Confirmation that the broad license in this parent repository applies to @hpd's ACES official configurations?

**Comment by hpd** [comment]
Confirmed.
HP

On Mon, Dec 7, 2015 at 9:40 AM, Troy James Sobotka <notifications@github.com

**Comment by aforsythe** [comment]
The ACES 1.0.1 OCIO config and the Python code included in @hpd's [OCIO Config fork] (https://github.com/hpd/OpenColorIO-Configs) have been submitted to the OCIO project via a pull request.  The config and code will be donated to the OCIO project under the terms of the [Sony Contributor's License Agreement] (http://opensource.imageworks.com/cla/).  

Until then, the [Academy's ACES licensing terms] (https://github.com/ampas/aces-dev/blob/master/LICENSE.md) should apply as the work was done under contract with the Academy.
