### ISSUE TITLE
AdobeRGB 1998 transfer curve missing from ACES OCIO Configs?

### ISSUE THREAD

**Issue by sobotka** [ampas/aces-dev#77]
It doesn't seem that there is an Adobe RGB 1998 transfer curve LUT defined in the configurations. Is it by design that the 2 51/256 curve was left out for loading Adobe RGB encoded imagery @hpd?

**Comment by hpd** [comment]
When I canvased users for non-ACES colorspaces that should be supported, the Adobe RGB 1998 space didn't come up. What workflows are you trying to support that require Adobe RGB 1998? The Academy, @aforsythe and @scottdyer, would like to know.

If you want to submit a pull request that adds support for that space, I would accept it.

**Comment by scottdyer** [comment]
Cleaning up old open issues...
This was an issue with the OCIO-Configs which are not hosted here.
