### ISSUE TITLE
Dropbox links are not working

### ISSUE THREAD

**Issue by awangk** [ampas/aces-dev#79]
E.g. for documentation and images.

**Comment by scottdyer** [comment]
@awangk I just tried the documentation and images links and they all seem to work on my end. Could you be more specific about which links were not working for you?

**Comment by RomBinDaHouse** [comment]
For example, the page https://github.com/ampas/aces-dev/tree/v1.0/documents contains link:
"ACES related documents are available as a ZIP ( http://j.mp/1CeRcLd ) (Download begins immediately)"
it leads to https://www.dropbox.com/sh/nt9z9m6utzvkc5m/AACEyKs7xCuhNdoGHGVBRsAsa?dl=1 and we get error 404 as a result

**Comment by scottdyer** [comment]
@RomBinDaHouse that is an old version of the documentation README so the link is no longer valid. Please see the updated documentation README at the current head of the master branch https://github.com/ampas/aces-dev/tree/master/documents
