### ISSUE TITLE
ACES Shaper LMT negative values via OCIO?

### ISSUE THREAD

**Issue by sobotka** [ampas/aces-dev#81]
Is anyone else getting negative values when rolling 0.0 footage through the ACES LMT Shaper to Linear?

Lowest value in the 1D LUT is 0.000175781256985, yet using ocioconvert on an EXR I see -0.01746?

**Comment by Dithermaster** [comment]
I don't have the config in front of me to check -- are you sure it's not
being run as an *inverse* 1D LUT? There is one case (IIRC, it's inverse)
where it extrapolates (in error, as the rest of OCIO LUT handling is
bounded), and with that starting value, a 0.0 in would be negative out.

On Sat, Mar 5, 2016 at 3:19 PM, Troy James Sobotka <notifications@github.com

**Comment by sobotka** [comment]
It's definitely an inverse.

Any chances we can shake the tree and get this fixed?

**Comment by Dithermaster** [comment]
I believe there is an old bug open on the extrapolation bug, and I also
have a fix I wrote for it a couple years ago I could submit as a PR.
However, I'm not sure how active folks are on the OCIO project to take the
PR.

On Sat, Mar 5, 2016 at 7:14 PM, Troy James Sobotka <notifications@github.com

**Comment by sobotka** [comment]
@shootfast? Can we see some life on OCIO on this please?

**Comment by Shootfast** [comment]
Hi, do you have the old bug report or a simple repro for me to play with? I'll see what I can do.

**Comment by sobotka** [comment]
As per previous post, inverse with 0.0 results in negatives.

**Comment by Dithermaster** [comment]
I think it is: https://github.com/imageworks/OpenColorIO/issues/326

**Comment by scottdyer** [comment]
Cleaning up old open issues...
This was an issue with the OCIO-Configs which are not hosted here.
This issue in particular appears to have been related to a bug in OCIO, as linked above.
