### ISSUE TITLE
Rec.709 ODT looks incorrect on consumer HDTVs

### ISSUE THREAD

**Issue by jasminpatry** [ampas/aces-dev#82]
My apologies if this is a FAQ, but I searched and didn't find it addressed elsewhere.

I'm finding that the output of the ODT.Academy.Rec709_100nits_dim.a1.0.1.ctl, when displayed on a late-model consumer HDTV, is significantly different from the output of ODT.Academy.RGBmonitor_D60sim_100nits_dim.a1.0.1.ctl viewed on a PC monitor.  I'm able to make them match very closely if I change the Rec709 ODT to encode using the Rec.709 OETF (item 1.2 in BT.709; also item 1.2 in Appendix 2 of BT.1886) instead of the inverse BT.1886 EOTF.

The attached images (which should be viewed on an sRGB PC monitor) are very good representations of what I'm seeing on the TV.

![bt1886_on_tv](https://cloud.githubusercontent.com/assets/1350715/14009014/d13b148a-f144-11e5-99c3-ee775fb427e0.png)
![rec709_on_tv](https://cloud.githubusercontent.com/assets/1350715/14009015/d73a58dc-f144-11e5-9e1e-b34ecc82a832.png)

Based on this, it seems to me that the Rec709 ODT should be using the Rec709 OETF. I understand that the standards specify a different (non-inverse) EOTF, but perhaps in practice TV manufacturers have adopted an EOTF that is intended to reproduce Rec709-encoded content?

Thanks!

**Comment by KevinJW** [comment]
I guess it depends on how good you think a "late-model consumer HDTV" is at correctly displaying images, or more specifically if they even attempt to model the conditions required for that specific CTL file.

That CTL is for a Rec 709/1886 display like a correctly calibrated 'HD Video' monitor (or my HDTV at home in 1886 mode in the appropriate viewing conditions).

Under the best interpretation of their actions the manufacturers are setting up their TVs in a way to best sell them under the typical environments they think they will be used, which is typically nothing like that of a typical mastering display, nor is it the exactly same as an sRGB monitor is specified to be under.

I think your requirement for matching the appearance of the two displays under side by side conditions is not something those CTFs are designed for, thus the images don't match

Kevin

**Comment by jasminpatry** [comment]
Hi Kevin,

Thanks for the explanation. Maybe I misunderstood the comment in the ODT that the CTL could be used for HDTV mastering. I took this to mean mastering content for consumers, who typically own "consumer HDTVs", and didn't figure that it was for a calibration profile that would look significantly different from what most consumer's TVs (which are usually not professionally calibrated) would produce.

My goal in opening this issue was as much to gain understanding as reporting a perceived "bug". For context, the ACES RRT and Rec709 ODT has begun to see adoption in my industry (video game development) as a "filmic tonemapping" curve (see for example https://knarkowicz.wordpress.com/2016/01/06/aces-filmic-tone-mapping-curve/ ). At my company, we are in the process of integrating it into our engine (via a curve fit similar to the one in the article), and I would like to do it "correctly", or at least take a principled approach to any changes we make. It worries me that there seems to be such a noticeable discrepancy between the 709/1886 standards (which the ACES 709 ODT seems to follow, as best as I can tell) and what ordinary uncalibrated TVs actually produce.

From my point of view, it seems I have two options:

1. Use the ODT as-is, and accept that our game will look incorrect on most consumer's TVs, but will be correct on the minority of "correctly-calibrated" TVs
2. Modify the ODT to produce output that looks more correct on most consumer's TVs, but will look incorrect on calibrated TVs

Neither of these options are very appealing, but I think that from a pragmatic point of view, option 2 would win out, as uneasy as that makes me. I'm hoping that I've missed something, though!

Thanks,
Jasmin

**Comment by st599** [comment]
HD Video should be viewed and quality assessed on a calibrated reference monitor under the correct viewing conditions.

The variability of TVs and viewing environments is too big to be able to cover.

**Comment by aforsythe** [comment]
From the standpoint of ACES development, we can only build transforms for device calibrations and view conditions which can be clearly specified.  We try to leverage standards and build ODTs for them rather then chase “real-world” physical devices and the measurement error associated with trying to characterize them.  If you can provide a clear specification of the device calibration and viewing conditions we can generate a test ODT for that device to determine if image appearance matches more closely or not.  Assuming it matches more closely we can then have a debate as to whether that ODT should be included in the official repository or not.

Alex


[?]<http://www.oscars.org>


Alex Forsythe
Image Engineering Manager


Academy of Motion Picture Arts and Sciences
Science & Technology Council
1313 Vine Street • Hollywood, CA 90028


323.817.4170 • aforsythe@oscars.org<mailto:aforsythe@oscars.org>

**Comment by jasminpatry** [comment]
Thanks for the feedback. After some investigation, I believe I can now explain what I was seeing.

- The PC monitors I've tested all exhibit non-standard gamma response, even when in "sRGB" mode. Specifically, the darker end of the curve has a gamma of about 2.6-3.0 depending on the monitor, while the lighter end of the curve was about 2.3-24.
- The TV I was using had a gamma curve closer to 2.2.
- The OOTF resulting from the Rec.709 OETF followed by the TV's 2.2 gamma curve is a very close match for the OOTF resulting from the sRGB OETF followed by the PC monitors' gamma curve, as shows by the plot below (sRGB axes, see [here](https://www.desmos.com/calculator/xb3n9ricbn) for an interactive version).

![xb3n9ricbn](https://cloud.githubusercontent.com/assets/1350715/21965299/1498aae6-db12-11e6-923b-d47a76045dd4.png)

Thanks,
Jasmin
