### ISSUE TITLE
Code duplication in "ACESlib.Tonescales.ctl".

### ISSUE THREAD

**Issue by KelSolaar** [ampas/aces-dev#97]
As I was rolling a Python version of some parts of the CTL codebase, I noticed some significant code duplication in the `transforms/ctl/lib/ACESlib.Tonescales.ctl` module, especially the `segmented_spline_c5_fwd` and `segmented_spline_c9_fwd` functions which are stricly the same except for the constant knots numbers:

![image](https://cloud.githubusercontent.com/assets/99779/22053222/254fadcc-ddb4-11e6-83af-52e85a4ed98d.png)

I was wondering if for maintenance purposes they could be refactored using a generic function which would take the knots numbers as argument.

I haven't checked the reverse implementation yet but I'm assuming they are similar too.

**Comment by aforsythe** [comment]
Thomas,

We will take a close look.  All the tonescale code may be going under significant revision soon. Regardless, thank you for reviewing the code so throughly.

Alex


[Δ]<http://www.oscars.org>


Alex Forsythe
Image Engineering Manager


Academy of Motion Picture Arts and Sciences
Science & Technology Council
1313 Vine Street • Hollywood, CA 90028


323.817.4170 • aforsythe@oscars.org<mailto:aforsythe@oscars.org>




>On Jan 17, 2017, at 10:29 PM, Thomas Mansencal <notifications@github.com<mailto:notifications@github.com>> wrote:


As I was rolling a Python version of some parts of the CTL codebase, I noticed some significant code duplication in the transforms/ctl/lib/ACESlib.Tonescales.ctl module, especially the segmented_spline_c5_fwd and segmented_spline_c9_fwd functions which are stricly the same except for the constant knots numbers:

[image]<https://cloud.githubusercontent.com/assets/99779/22053222/254fadcc-ddb4-11e6-83af-52e85a4ed98d.png>

I was wondering if for maintenance purposes they could be refactored using a generic function which would take the knots numbers as argument.

I haven't checked the reverse implementation yet but I'm assuming they are similar too.

**Comment by KelSolaar** [comment]
Thanks @aforsythe! 👍

**Comment by scottdyer** [comment]
I can't exactly recall why I left this duplication in there, but there was a reason. I believe it had to do with the annoying requirement to keep the commented code fragments around for backward compatibility w/ versions of CTL < 1.5. However, looking at this, I realize that I don't think the c5 function would run if that section were uncommented (I left references up to coefficient 9 in there, which would be out of range). Yes, in the future, I would love to consolidate this. 
Let's keep this issue open as a reminder to address this in a future update.

**Comment by KelSolaar** [comment]
> Let's keep this issue open as a reminder to address this in a future update.

Great thanks!
